version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    container_name: tracking-mysql
    restart: always
    environment:
      MYSQL_DATABASE: tracking_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tracking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tracking-backend
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tracking_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API_EXTERNAL_URL: https://desafio-media.onrender.com
      API_EXTERNAL_KEY: m4a_9d7f2c1ab84e6f03b2c91d5aa77e4c6f8b1d2e3f4a5b6c7
    ports:
      - "8080:8080"
    networks:
      - tracking-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tracking-frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "4200:80"
    networks:
      - tracking-network

networks:
  tracking-network:
    driver: bridge

volumes:
  mysql_data: