spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/tracking_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.external.url=${API_EXTERNAL_URL:https://desafio-media.onrender.com}
api.external.key=${API_EXTERNAL_KEY:m4a_9d7f2c1ab84e6f03b2c91d5aa77e4c6f8b1d2e3f4a5b6c7}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never